---
version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: actions
      include: scope
    labels:
      - type/dependencies
      - update/github-workflows
      - release/chore
