---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
        name: Check for merge conflicts before committing
      - id: check-case-conflict
        name: Check for case conflicts for case-sensitive filesystems
      - id: check-symlinks
        name: Check for broken syslinks in the repository
      - id: destroyed-symlinks
        name: Check for destroyed symlinks in the repository
      - id: check-added-large-files
        name: Check no large files have been added to the commit
      - id: trailing-whitespace
        name: Check all trailing whitespace is removed
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
        name: Check all files end in a new-line only

  - repo: https://github.com/python-jsonschema/check-jsonschema.git
    rev: 0.23.0
    hooks:
      - name: Check the GitHub Workflows for correctness
        id: check-github-workflows

  - repo: https://github.com/igorshubovych/markdownlint-cli.git
    rev: v0.34.0
    hooks:
      - id: markdownlint
        name: Check Markdown correctness and formatting

  - repo: https://github.com/zricethezav/gitleaks.git
    rev: v8.16.3
    hooks:
      - id: gitleaks
        name: Check for hard-coded secrets, keys, and credentials
